apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teemii

spec:
  interval: 5m

  chart:
    spec:
      chart: ./charts/teemii
      sourceRef:
        kind: HelmRepository
        name: teemii-helm-chart
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: teemii-values
      valuesKey: values.yaml
